language: java
jdk: oraclejdk7
before_install:
    - git clone git@github.com:mosabua/maven-android-sdk-deployer.git
    - cd maven-android-sdk-deployer
    - mvn install -P 4.3
    
install:
    - mvn install -DskipTests=true
    
script:
    - mvn test

